package com.inputleaf.android.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Leaf-green M3 schemes for devices without dynamic color (Android 11 and below).
val LeafLightColorScheme = lightColorScheme(
    primary = Color(0xFF386A20),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB8F397),
    onPrimaryContainer = Color(0xFF205107),
    secondary = Color(0xFF55624C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD9E7CB),
    onSecondaryContainer = Color(0xFF3E4A36),
    tertiary = Color(0xFF386667),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBBEBEC),
    onTertiaryContainer = Color(0xFF1E4E4E),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF8FAF0),
    onBackground = Color(0xFF191D16),
    surface = Color(0xFFF8FAF0),
    onSurface = Color(0xFF191D16),
    surfaceVariant = Color(0xFFE0E4D6),
    onSurfaceVariant = Color(0xFF43483E),
    outline = Color(0xFF74796D),
    outlineVariant = Color(0xFFC4C8BA),
    inverseSurface = Color(0xFF2E312B),
    inverseOnSurface = Color(0xFFEFF2E7),
    inversePrimary = Color(0xFF9DD67D),
    surfaceDim = Color(0xFFD8DBD1),
    surfaceBright = Color(0xFFF8FAF0),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F5EA),
    surfaceContainer = Color(0xFFECEFE4),
    surfaceContainerHigh = Color(0xFFE7E9DF),
    surfaceContainerHighest = Color(0xFFE1E4D9),
)

val LeafDarkColorScheme = darkColorScheme(
    primary = Color(0xFF9DD67D),
    onPrimary = Color(0xFF0B3900),
    primaryContainer = Color(0xFF205107),
    onPrimaryContainer = Color(0xFFB8F397),
    secondary = Color(0xFFBDCBB0),
    onSecondary = Color(0xFF283420),
    secondaryContainer = Color(0xFF3E4A36),
    onSecondaryContainer = Color(0xFFD9E7CB),
    tertiary = Color(0xFFA0CFD0),
    onTertiary = Color(0xFF003738),
    tertiaryContainer = Color(0xFF1E4E4E),
    onTertiaryContainer = Color(0xFFBBEBEC),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF11140E),
    onBackground = Color(0xFFE1E4D9),
    surface = Color(0xFF11140E),
    onSurface = Color(0xFFE1E4D9),
    surfaceVariant = Color(0xFF43483E),
    onSurfaceVariant = Color(0xFFC4C8BA),
    outline = Color(0xFF8E9286),
    outlineVariant = Color(0xFF43483E),
    inverseSurface = Color(0xFFE1E4D9),
    inverseOnSurface = Color(0xFF2E312B),
    inversePrimary = Color(0xFF386A20),
    surfaceDim = Color(0xFF11140E),
    surfaceBright = Color(0xFF373A33),
    surfaceContainerLowest = Color(0xFF0C0F09),
    surfaceContainerLow = Color(0xFF191D16),
    surfaceContainer = Color(0xFF1D211A),
    surfaceContainerHigh = Color(0xFF282B24),
    surfaceContainerHighest = Color(0xFF32362F),
)
